### ISSUE TITLE
Erro: A rota não existe! :(

### ISSUE THREAD

**Issue by pwrslv3** [adimael/registro_de_chaves_portaria#2]
Consegui rodar 100% na máquina local, usando o Xampp, mas ao tentar rodar em servidor remoto(Hostinger) dá a mensagem de "Erro: A rota não existe! :("
A impressão é que o arquivo index.php não consegue direcionar pra dashboard.
Tem ideia de qual configuração pode ser necessário ajustar pra rodar nessa condição ?

**Comment by adimael** [comment]
Olá, existe algumas possiveis causas pra isso tá acontecendo. Pode ser que a Hostinger não esteja configurado corretamente para lidar com as regras de roteamento. Você pode tentar realizar alguma alteração no arquivo .htaccess do projeto para ver se consegue resolver. Configurações de ambiente do servidor da Hostinger tambem pode causar esse tipos de problemas.
